/**
 *
 * $Id$
 */
package Sequencediagram.sequencediagram.validation;

import Sequencediagram.sequencediagram.InteractionFragment;
import Sequencediagram.sequencediagram.LifeLine;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Sequencediagram.sequencediagram.SequenceDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceDiagramValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateLifeLines(EList<LifeLine> value);
	boolean validateFragments(EList<InteractionFragment> value);
}
