/**
 *
 * $Id$
 */
package Efsm.efsm.validation;

import Efsm.efsm.ContextVariable;
import Efsm.efsm.InitialState;
import Efsm.efsm.State;
import Efsm.efsm.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Efsm.efsm.EFSM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EFSMValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateTransitions(EList<Transition> value);

	boolean validateInitialstate(InitialState value);

	boolean validateStates(EList<State> value);

	boolean validateVariables(EList<ContextVariable> value);
}
