/**
 *
 * $Id$
 */
package Efsm.efsm.validation;

import Efsm.efsm.AbstractState;

/**
 * A sample validator interface for {@link Efsm.efsm.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateInput(String value);

	boolean validateOutput(String value);

	boolean validateSource(AbstractState value);

	boolean validateTarget(AbstractState value);

	boolean validateEvent(String value);

	boolean validateGuard(String value);

	boolean validateAction(String value);
}
